#!/usr/bin/env bash
# compose-global-claude-md.sh — Compose ~/.claude/CLAUDE.md from
# shared (public) and local (private) sections.
#
# The shared section lives in the public repo and contains coding
# standards, conventions, and methodology — safe to show others.
# The local section lives in pa-data and contains network topology,
# server specs, and operational guardrails — private.
#
# Usage:
#   bash scripts/compose-global-claude-md.sh
#   bash scripts/compose-global-claude-md.sh --dry-run

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PA_DIR="$(dirname "$SCRIPT_DIR")"

SHARED="$PA_DIR/global-claude-md/shared.md"
LOCAL="$PA_DIR/data/global-claude-md/local.md"
TARGET="${HOME}/.claude/CLAUDE.md"

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
fi

# Verify source files exist
if [[ ! -f "$SHARED" ]]; then
    echo "ERROR: Shared section not found: $SHARED" >&2
    exit 1
fi

if [[ ! -f "$LOCAL" ]]; then
    echo "ERROR: Local section not found: $LOCAL" >&2
    echo "  (Is the data submodule initialised? Run: git submodule update --init)" >&2
    exit 1
fi

# Compose the file.
#
# Audit 2026-05-02 E-Medium: previous implementation captured each source
# file via `$(cat …)`, which strips trailing newlines (POSIX text-file
# convention violated) and then silently overwrote any user edits to the
# generated file. We now (a) prepend a generated-file banner so users see
# the file is mechanically composed, and (b) stream the inputs through
# `cat` directly to preserve trailing newlines.
GENERATED_BANNER="<!--
  Generated by scripts/compose-global-claude-md.sh — do not edit by hand.
  Edit the source files instead:
    shared: ${SHARED}
    local:  ${LOCAL}
  Any direct edits to this file will be silently overwritten on the next
  sync (sync-symlinks.sh runs the composer at the end of every daily-sync
  and at every SessionStart).
-->
"

if $DRY_RUN; then
    echo "=== Would write to: $TARGET ==="
    {
        printf '%s\n' "$GENERATED_BANNER"
        cat "$SHARED"
        printf '\n'
        cat "$LOCAL"
    } | head -10
    echo "..."
    {
        printf '%s\n' "$GENERATED_BANNER"
        cat "$SHARED"
        printf '\n'
        cat "$LOCAL"
    } | tail -5
    echo ""
    composed_lines=$({
        printf '%s\n' "$GENERATED_BANNER"
        cat "$SHARED"
        printf '\n'
        cat "$LOCAL"
    } | wc -l)
    echo "Total lines: $composed_lines"
else
    mkdir -p "$(dirname "$TARGET")"
    # Stream-write to preserve trailing newlines (no command substitution
    # means no trailing-newline strip). A blank line separates the banner
    # from the shared section, and another separates shared from local.
    {
        printf '%s\n' "$GENERATED_BANNER"
        cat "$SHARED"
        printf '\n'
        cat "$LOCAL"
    } > "$TARGET"
    echo "Composed ~/.claude/CLAUDE.md from:"
    echo "  shared: $SHARED ($(wc -l < "$SHARED") lines)"
    echo "  local:  $LOCAL ($(wc -l < "$LOCAL") lines)"
    echo "  output: $TARGET ($(wc -l < "$TARGET") lines)"
fi
