#!/usr/bin/env bash
# compose-global-claude-md.sh — Compose ~/.claude/CLAUDE.md from the shared
# (portable), Claude-overlay, and local (private) instruction sources.
#
# Layering (Sol-integration plan §6, Phase 2):
#   1. global-agent-guidance/common.md   — portable, agent-neutral guidance.
#      SHARED editing surface: Claude and Sol may both propose changes to it,
#      and Sol's gpt-hub installer composes the same file into
#      ~/.codex/AGENTS.md. Nothing harness-specific belongs here.
#   2. global-claude-md/claude.md        — Claude-owned overlay: commands,
#      tools, models, and Claude-owned stores. Never read by Sol's composer.
#   3. data/global-claude-md/local.md    — private machine detail (network
#      topology, server guardrails), from the pa-data submodule.
#
# This composer writes only Claude's output. It must never write
# ~/.codex/AGENTS.md, and Sol's installer must never write ~/.claude/CLAUDE.md.
#
# Usage:
#   bash scripts/compose-global-claude-md.sh
#   bash scripts/compose-global-claude-md.sh --dry-run

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PA_DIR="$(dirname "$SCRIPT_DIR")"

COMMON="$PA_DIR/global-agent-guidance/common.md"
OVERLAY="$PA_DIR/global-claude-md/claude.md"
LOCAL="$PA_DIR/data/global-claude-md/local.md"
TARGET="${HOME}/.claude/CLAUDE.md"

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
fi

# Verify source files exist.
if [[ ! -f "$COMMON" ]]; then
    echo "ERROR: Shared common section not found: $COMMON" >&2
    exit 1
fi

if [[ ! -f "$OVERLAY" ]]; then
    echo "ERROR: Claude overlay not found: $OVERLAY" >&2
    exit 1
fi

if [[ ! -f "$LOCAL" ]]; then
    echo "ERROR: Local section not found: $LOCAL" >&2
    echo "  (Is the data submodule initialised? Run: git submodule update --init)" >&2
    exit 1
fi

# Compose the file.
#
# Audit 2026-05-02 E-Medium: a previous implementation captured each source
# file via `$(cat …)`, which strips trailing newlines (POSIX text-file
# convention violated) and then silently overwrote any user edits to the
# generated file. We now (a) prepend a generated-file banner so users see
# the file is mechanically composed, and (b) stream the inputs through
# `cat` directly to preserve trailing newlines.
GENERATED_BANNER="<!--
  Generated by scripts/compose-global-claude-md.sh — do not edit by hand.
  Edit the source files instead:
    common (shared with Sol): ${COMMON}
    Claude overlay:           ${OVERLAY}
    local (private):          ${LOCAL}
  Any direct edits to this file will be silently overwritten on the next
  sync (sync-symlinks.sh runs the composer at the end of every daily-sync
  and at every SessionStart).
-->
"

# Emit the composed document on stdout. Blank lines separate the banner and
# each source section.
compose() {
    printf '%s\n' "$GENERATED_BANNER"
    cat "$COMMON"
    printf '\n'
    cat "$OVERLAY"
    printf '\n'
    cat "$LOCAL"
}

if $DRY_RUN; then
    # Materialise once to a temporary file. Piping `compose` straight into
    # `head` makes `head` close the pipe early, which under `set -o pipefail`
    # fails the whole script with SIGPIPE (exit 141) — a latent bug in the
    # pre-Phase-2 version of this script.
    PREVIEW="$(mktemp)"
    trap 'rm -f "$PREVIEW"' EXIT
    compose > "$PREVIEW"
    echo "=== Would write to: $TARGET ==="
    head -10 "$PREVIEW"
    echo "..."
    tail -5 "$PREVIEW"
    echo ""
    echo "Total lines: $(wc -l < "$PREVIEW")"
    echo "Total bytes: $(wc -c < "$PREVIEW")"
else
    mkdir -p "$(dirname "$TARGET")"
    compose > "$TARGET"
    echo "Composed ~/.claude/CLAUDE.md from:"
    # Byte counts matter for the cross-harness instruction budget (plan §6):
    # common.md is also loaded by Codex, where oversized global instructions
    # silently displace nearer, more specific project files.
    printf '  common:  %s (%s lines, %s bytes)\n' \
        "$COMMON" "$(wc -l < "$COMMON")" "$(wc -c < "$COMMON")"
    printf '  overlay: %s (%s lines, %s bytes)\n' \
        "$OVERLAY" "$(wc -l < "$OVERLAY")" "$(wc -c < "$OVERLAY")"
    printf '  local:   %s (%s lines, %s bytes)\n' \
        "$LOCAL" "$(wc -l < "$LOCAL")" "$(wc -c < "$LOCAL")"
    printf '  output:  %s (%s lines, %s bytes)\n' \
        "$TARGET" "$(wc -l < "$TARGET")" "$(wc -c < "$TARGET")"
fi
